### ISSUE TITLE
Make graphic functions work

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#50]
Graphic functions are currently desactivated in `autogen/generator.py` (see the `function_blacklist` defined at [line 55](https://github.com/defeo/cypari2/blob/master/autogen/generator.py#L55)). We should be able to use them in both console mode and Jupyter.

**Comment by jdemeyer** [comment]
That will work only with PARI-2.10 or later. The reason is that graphics in PARI versions <= 2.9 are implemented in the GP program and not in the PARI library. I worked on that because I wanted those graphics functions in my Jupyter kernel. Now all graphics functions are implemented in the PARI library.

Maybe I'll work on this at the PARI/GP atelier.

**Comment by jdemeyer** [comment]
Working on this in #53

**Comment by jdemeyer** [comment]
> We should be able to use them in both console mode

How can you show images in console mode? I don't see how that could technically work.

**Comment by videlec** [comment]
- writing in files?
- pop-up windows?

At least `matplotlib` and `Sage` managed it.
