### ISSUE TITLE
Running doctests without installing cypari2

### ISSUE THREAD

**Issue by tobihan** [defeo/cypari2#60]
Hi,

for the Debian package it would be nice if we could run the doctests after the build, without installing cypari2. I'm getting this

    ./tests/rundoctest.py 
    Traceback (most recent call last):
      File "./tests/rundoctest.py", line 11, in <module>
        import cypari2
      File "/home/thansen/src/sage/cypari2/cypari2/cypari2/__init__.py", line 1, in <module>
        from .pari_instance import Pari
    ImportError: No module named pari_instance

Any hints what I need to do to make this work?

Thanks,
Tobias

**Comment by jdemeyer** [comment]
> it would be nice if we could run the doctests after the build, without installing cypari2.

What does that even mean? `pip` does build and install together.

**Comment by jdemeyer** [comment]
@embray This is really a Python question.

**Comment by videlec** [comment]
@tobihan  How do you build `cypari2`? For example, with
```
$ python setup.py build_ext --inplace
```
The tests just work fine (without installing).

**Comment by tobihan** [comment]
Ah, sorry for the noise. The Debian scripts do everything automatically so I first had to figure out what happens. At the time the tests are run the package is installed only in a temporary hidden folder. When I add that to the Python path the tests work.

**Comment by embray** [comment]
In my experience it's nice to add a `setup.py test` command which also automatically invokes `setup.py build_ext --inplace` if needed, and imports/runs the tests directly from the source code.

This, of course, means designing the package to be able to run directly from the source tree, which I prefer to be able to do anyways.  An alternative is to design it to run out of the build/ directory so that you can avoid cluttering the source tree. But this is a bit trickier to get right I think.
