### ISSUE TITLE
methods vs functions

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#8]
Currently and mostly for historical reasons, cypari2 works with methods instead of functions. For example `pari(2).zeta()` instead of `pari.zeta(2)`. It makes a big difference with the GP language that might be some trouble for PARI users. It should not be hard to implement a functional version using script for automatic generation.

The user interface might be something like

    >>> from cypari2.functions import *
    >>> zeta(2)
    1.64493406684823

**Comment by jdemeyer** [comment]
I think that this is fairly easy to do, but I want to do it **after** spltiting cypari2 from Sage.

**Comment by defeo** [comment]
Adding some PARI functions to the list of those that would make much more sense as functions rather than methods:

- `nextprime`
- `nfinit`, `bnfinit`, `galoisinit` ...
- `ffgen`

I think these should be attached also to the `PariInstance` object, not only in a _hidden_ `.functions` module. Do we have an easy way to do this automatically?

**Comment by jdemeyer** [comment]
> Do we have an easy way to do this automatically?

Yes. See my previous comment.

**Comment by defeo** [comment]
> Yes. See my previous comment.

?? Your comment doesn't say anything on "automatically" (except "easy", maybe?)

**Comment by jdemeyer** [comment]
I'm just saying that it should be easy to automatically make *all* PARI functions available as methods of `Pari()`.

**Comment by defeo** [comment]
Oh. _all_ should be easy, and probably also desirable, that's right.

**Comment by jdemeyer** [comment]
Fixed by #24.
